### ISSUE TITLE
Autocomplete text does not show with the zsh shell

### ISSUE THREAD

**Issue by isheebo** [MatchaScript/zunda#1]
First off, I would like to say that this is a great theme and I love it. However, when using the [zsh shell](https://en.wikipedia.org/wiki/Z_shell) via the terminal window(Control + ~ on  a MacOSx) , the terminal autocomplete text cannot be seen. You only see the text you are typing but not the generated possible line completions. _(these are all hidden in black)_

Included is an image to point out the differences.

With the default dark theme, You can see all the impending autocompleted text, that is, `git checkout .`
<img width="1140" alt="Default dark" src="https://user-images.githubusercontent.com/29917291/97335799-4dd31080-188f-11eb-97ec-16e2b08d1583.png">

With Zunda, you can only see the words you type, in this case `git c`
<img width="1157" alt="zunda theme" src="https://user-images.githubusercontent.com/29917291/97335863-617e7700-188f-11eb-9bc4-40527d7f31f7.png">

**Comment by MatchaScript** [comment]
@isheebo It's a bug alright. I'll get to it soon. thanks!

**Comment by MatchaScript** [comment]
Fixed! Please update
